site_name: MADI Raspisanie API
site_author: Potapchuk Danila
repo_url: https://github.com/1mk0v/MADI-Raspisanie-API
repo_name: 1mk0v/madi-raspisanie-api
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: images/ico.svg
  favicon: images/ico.svg
  palette: 
    # Palette toggle for light mode
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - content.code.copy


extra:
  homepage: http://127.0.0.1:8000/ru/home
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/nivicki
      name: Send message to telegram
    - icon: fontawesome/solid/envelope
      link: mailto:potapchuk01@mail.ru
      name: Send message to mail


markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html


nav:
  - Home: home.md
  - Source: 
    - How it works: source/hit.md
    # - Requests: source/requests.md
    # - Individual Generator: source/generator.md
    # - Bridge: source/bridge.md
  - API: api.md
